/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.*;
import javax.swing.GroupLayout;
import controller.FileHandler;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import model.Estagiario;
import model.Funcionario;

/**
 *
 * @author Computacao
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuRegister = new javax.swing.JMenu();
        mItemCadastroFuncionario = new javax.swing.JMenuItem();
        mItemCadastroEstagiario = new javax.swing.JMenuItem();
        menuView = new javax.swing.JMenu();
        mItemVisualizarFuncionario = new javax.swing.JMenuItem();
        mItemVisualizarEstagiario = new javax.swing.JMenuItem();
        menuDelete = new javax.swing.JMenu();
        mItemDelete = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuRegister.setText("Cadastro");

        mItemCadastroFuncionario.setText("Funcionario");
        mItemCadastroFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemCadastroFuncionarioActionPerformed(evt);
            }
        });
        menuRegister.add(mItemCadastroFuncionario);

        mItemCadastroEstagiario.setText("Estagiario");
        mItemCadastroEstagiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemCadastroEstagiarioActionPerformed(evt);
            }
        });
        menuRegister.add(mItemCadastroEstagiario);

        jMenuBar1.add(menuRegister);

        menuView.setText("Visualizar");

        mItemVisualizarFuncionario.setText("Funcionario");
        mItemVisualizarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemVisualizarFuncionarioActionPerformed(evt);
            }
        });
        menuView.add(mItemVisualizarFuncionario);

        mItemVisualizarEstagiario.setText("Estagiario");
        mItemVisualizarEstagiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemVisualizarEstagiarioActionPerformed(evt);
            }
        });
        menuView.add(mItemVisualizarEstagiario);

        jMenuBar1.add(menuView);

        menuDelete.setText("Deletar");

        mItemDelete.setText("Deletar");
        mItemDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemDeleteActionPerformed(evt);
            }
        });
        menuDelete.add(mItemDelete);

        jMenuBar1.add(menuDelete);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 609, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mItemCadastroFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemCadastroFuncionarioActionPerformed
        CadastroFuncionario cadastroFuncionario = new CadastroFuncionario();
        cadastroFuncionario.setVisible(true);
    }//GEN-LAST:event_mItemCadastroFuncionarioActionPerformed

    private void mItemCadastroEstagiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemCadastroEstagiarioActionPerformed
        CadastroEstagiario cadastroEstagiario = new CadastroEstagiario();
        cadastroEstagiario.setVisible(true);
    }//GEN-LAST:event_mItemCadastroEstagiarioActionPerformed

    private void mItemVisualizarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemVisualizarFuncionarioActionPerformed
        FileHandler<Funcionario> fileHandler = new FileHandler();
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Selecione o arquivo");
        
        int opt = fileChooser.showOpenDialog(this);
        if (opt == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String filename = selectedFile.getAbsolutePath();
            
            try {
                Funcionario funcionario = fileHandler.read(filename);
                
                VisualizarFuncionario visualizarFuncionario = new VisualizarFuncionario();
                visualizarFuncionario.setFuncionario(funcionario);
                
                visualizarFuncionario.setVisible(true);
                visualizarFuncionario.showContent();
            } catch (IOException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_mItemVisualizarFuncionarioActionPerformed

    private void mItemVisualizarEstagiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemVisualizarEstagiarioActionPerformed
        FileHandler<Estagiario> fileHandler = new FileHandler();
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Selecione o arquivo");
        
        int opt = fileChooser.showOpenDialog(this);
        if (opt == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String filename = selectedFile.getAbsolutePath();
            
            try {
                Estagiario estagiario = fileHandler.read(filename);
                
                VisualizarEstagiario visualizarEstagiario = new VisualizarEstagiario();
                visualizarEstagiario.setEstagiario(estagiario);
                
                visualizarEstagiario.setVisible(true);
                visualizarEstagiario.showContent();
            } catch (IOException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_mItemVisualizarEstagiarioActionPerformed

    private void mItemDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemDeleteActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogType(0);
        fileChooser.setApproveButtonText("Deletar");
        fileChooser.setDialogTitle("Selecione o arquivo");
        
        int opt = fileChooser.showDialog(this, null);
        if (opt == JFileChooser.APPROVE_OPTION) {
            int confirm = JOptionPane.showConfirmDialog(fileChooser, "Confirmar exclusão?");
            if (confirm == JOptionPane.YES_OPTION) {
                File selectedFile = fileChooser.getSelectedFile();
                boolean operation = selectedFile.delete();
            }
        }
    }//GEN-LAST:event_mItemDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mItemCadastroEstagiario;
    private javax.swing.JMenuItem mItemCadastroFuncionario;
    private javax.swing.JMenuItem mItemDelete;
    private javax.swing.JMenuItem mItemVisualizarEstagiario;
    private javax.swing.JMenuItem mItemVisualizarFuncionario;
    private javax.swing.JMenu menuDelete;
    private javax.swing.JMenu menuRegister;
    private javax.swing.JMenu menuView;
    // End of variables declaration//GEN-END:variables
}
